---
title: "git_00"
author: "Eileen Dunn"  
date: "July 23,2024"  
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!--> 

’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  

“Beware the Jabberwock, my son!  
      The jaws that bite, the claws that   catch!  
Beware the Jubjub bird, and shun  
      The frumious Bandersnatch!”  


## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

The sun was shining on the sea,  
      Shining with all his might:  

## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

Nature’s first green is gold,  
Her hardest hue to hold.  
Her early leaf’s a flower;  
But only so an hour.  
Then leaf subsides to leaf.  
So Eden sank to grief,  
So dawn goes down to day.  
Nothing gold can stay.  
